#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v18
# autospec commit: f35655a
#
# Source0 file verified with key 0x2C8DF587A6D4AAC1 (nicolas.fella@kde.org)
#
Name     : threadweaver
Version  : 6.5.0
Release  : 84
URL      : https://download.kde.org/stable/frameworks/6.5/threadweaver-6.5.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/6.5/threadweaver-6.5.0.tar.xz
Source1  : https://download.kde.org/stable/frameworks/6.5/threadweaver-6.5.0.tar.xz.sig
Source2  : 2C8DF587A6D4AAC1.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0 LGPL-2.0 LGPL-2.1
Requires: threadweaver-lib = %{version}-%{release}
Requires: threadweaver-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# ThreadWeaver
Helper for multithreaded programming
## Introduction
ThreadWeaver is a helper for multithreaded programming.  It uses a job-based
interface to queue tasks and execute them in an efficient way.

%package dev
Summary: dev components for the threadweaver package.
Group: Development
Requires: threadweaver-lib = %{version}-%{release}
Provides: threadweaver-devel = %{version}-%{release}
Requires: threadweaver = %{version}-%{release}

%description dev
dev components for the threadweaver package.


%package lib
Summary: lib components for the threadweaver package.
Group: Libraries
Requires: threadweaver-license = %{version}-%{release}

%description lib
lib components for the threadweaver package.


%package license
Summary: license components for the threadweaver package.
Group: Default

%description license
license components for the threadweaver package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 2C8DF587A6D4AAC1' gpg.status
%setup -q -n threadweaver-6.5.0
cd %{_builddir}/threadweaver-6.5.0
pushd ..
cp -a threadweaver-6.5.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1723238868
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1723238868
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/threadweaver
cp %{_builddir}/threadweaver-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/threadweaver/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/threadweaver-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/threadweaver/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/threadweaver-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/threadweaver/20079e8f79713dce80ab09774505773c926afa2a || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/KF6/ThreadWeaver/ThreadWeaver/Collection
/usr/include/KF6/ThreadWeaver/ThreadWeaver/DebuggingAids
/usr/include/KF6/ThreadWeaver/ThreadWeaver/Dependency
/usr/include/KF6/ThreadWeaver/ThreadWeaver/DependencyPolicy
/usr/include/KF6/ThreadWeaver/ThreadWeaver/DestructedState
/usr/include/KF6/ThreadWeaver/ThreadWeaver/Exception
/usr/include/KF6/ThreadWeaver/ThreadWeaver/IdDecorator
/usr/include/KF6/ThreadWeaver/ThreadWeaver/InConstructionState
/usr/include/KF6/ThreadWeaver/ThreadWeaver/Job
/usr/include/KF6/ThreadWeaver/ThreadWeaver/JobInterface
/usr/include/KF6/ThreadWeaver/ThreadWeaver/JobPointer
/usr/include/KF6/ThreadWeaver/ThreadWeaver/Lambda
/usr/include/KF6/ThreadWeaver/ThreadWeaver/ManagedJobPointer
/usr/include/KF6/ThreadWeaver/ThreadWeaver/QObjectDecorator
/usr/include/KF6/ThreadWeaver/ThreadWeaver/Queue
/usr/include/KF6/ThreadWeaver/ThreadWeaver/QueueAPI
/usr/include/KF6/ThreadWeaver/ThreadWeaver/QueueInterface
/usr/include/KF6/ThreadWeaver/ThreadWeaver/QueuePolicy
/usr/include/KF6/ThreadWeaver/ThreadWeaver/QueueSignals
/usr/include/KF6/ThreadWeaver/ThreadWeaver/QueueStream
/usr/include/KF6/ThreadWeaver/ThreadWeaver/Queueing
/usr/include/KF6/ThreadWeaver/ThreadWeaver/ResourceRestrictionPolicy
/usr/include/KF6/ThreadWeaver/ThreadWeaver/Sequence
/usr/include/KF6/ThreadWeaver/ThreadWeaver/ShuttingDownState
/usr/include/KF6/ThreadWeaver/ThreadWeaver/State
/usr/include/KF6/ThreadWeaver/ThreadWeaver/SuspendedState
/usr/include/KF6/ThreadWeaver/ThreadWeaver/SuspendingState
/usr/include/KF6/ThreadWeaver/ThreadWeaver/Thread
/usr/include/KF6/ThreadWeaver/ThreadWeaver/ThreadWeaver
/usr/include/KF6/ThreadWeaver/ThreadWeaver/Weaver
/usr/include/KF6/ThreadWeaver/ThreadWeaver/WeaverImplState
/usr/include/KF6/ThreadWeaver/ThreadWeaver/WeaverInterface
/usr/include/KF6/ThreadWeaver/ThreadWeaver/WorkingHardState
/usr/include/KF6/ThreadWeaver/threadweaver/collection.h
/usr/include/KF6/ThreadWeaver/threadweaver/debuggingaids.h
/usr/include/KF6/ThreadWeaver/threadweaver/dependency.h
/usr/include/KF6/ThreadWeaver/threadweaver/dependencypolicy.h
/usr/include/KF6/ThreadWeaver/threadweaver/destructedstate.h
/usr/include/KF6/ThreadWeaver/threadweaver/exception.h
/usr/include/KF6/ThreadWeaver/threadweaver/iddecorator.h
/usr/include/KF6/ThreadWeaver/threadweaver/inconstructionstate.h
/usr/include/KF6/ThreadWeaver/threadweaver/job.h
/usr/include/KF6/ThreadWeaver/threadweaver/jobinterface.h
/usr/include/KF6/ThreadWeaver/threadweaver/jobpointer.h
/usr/include/KF6/ThreadWeaver/threadweaver/lambda.h
/usr/include/KF6/ThreadWeaver/threadweaver/managedjobpointer.h
/usr/include/KF6/ThreadWeaver/threadweaver/qobjectdecorator.h
/usr/include/KF6/ThreadWeaver/threadweaver/queue.h
/usr/include/KF6/ThreadWeaver/threadweaver/queueapi.h
/usr/include/KF6/ThreadWeaver/threadweaver/queueing.h
/usr/include/KF6/ThreadWeaver/threadweaver/queueinterface.h
/usr/include/KF6/ThreadWeaver/threadweaver/queuepolicy.h
/usr/include/KF6/ThreadWeaver/threadweaver/queuesignals.h
/usr/include/KF6/ThreadWeaver/threadweaver/queuestream.h
/usr/include/KF6/ThreadWeaver/threadweaver/resourcerestrictionpolicy.h
/usr/include/KF6/ThreadWeaver/threadweaver/sequence.h
/usr/include/KF6/ThreadWeaver/threadweaver/shuttingdownstate.h
/usr/include/KF6/ThreadWeaver/threadweaver/state.h
/usr/include/KF6/ThreadWeaver/threadweaver/suspendedstate.h
/usr/include/KF6/ThreadWeaver/threadweaver/suspendingstate.h
/usr/include/KF6/ThreadWeaver/threadweaver/thread.h
/usr/include/KF6/ThreadWeaver/threadweaver/threadweaver.h
/usr/include/KF6/ThreadWeaver/threadweaver/threadweaver_export.h
/usr/include/KF6/ThreadWeaver/threadweaver/weaver.h
/usr/include/KF6/ThreadWeaver/threadweaver/weaverimplstate.h
/usr/include/KF6/ThreadWeaver/threadweaver/weaverinterface.h
/usr/include/KF6/ThreadWeaver/threadweaver/workinghardstate.h
/usr/include/KF6/ThreadWeaver/threadweaver_version.h
/usr/lib64/cmake/KF6ThreadWeaver/KF6ThreadWeaverConfig.cmake
/usr/lib64/cmake/KF6ThreadWeaver/KF6ThreadWeaverConfigVersion.cmake
/usr/lib64/cmake/KF6ThreadWeaver/KF6ThreadWeaverTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6ThreadWeaver/KF6ThreadWeaverTargets.cmake
/usr/lib64/libKF6ThreadWeaver.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libKF6ThreadWeaver.so.6.5.0
/usr/lib64/libKF6ThreadWeaver.so.6
/usr/lib64/libKF6ThreadWeaver.so.6.5.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/threadweaver/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/threadweaver/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/threadweaver/9a1929f4700d2407c70b507b3b2aaf6226a9543c
